server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

zuul:
  #过滤客户端请求中的和该配置项匹配的headers
  sensitive-headers:
  routes:
    default:
      path: /**
      serviceId: crbookindex
